const nbaCardsData = [
  {
    id: 1,
    img: "./img/Raptors.webp",
    name: "Raptors",
    country: 'Canada',
    city: "Toronto",
    champions: 1,
    currentPosition: 9,
    ticketPrice: "from 45$",
    priceForUkr: "from 15$",
    fanRate: 3.5,
  },
  {
    id: 2,
    img: "./img/Lakers.webp",
    name: 'Lakers',
    country: 'USA',
    city: "Los-Angeles",
    champions: 17,
    currentPosition: 7,
    ticketPrice: "from 35$",
    fanRate: 4,
  },
  {
    id: 3,
    img: "./img/Celtics.webp",
    name: "Celtics",
    country: 'USA',
    city: "Boston",
    champions: 12,
    currentPosition: 2,
    ticketPrice: "from 42$",
    priceForUkr: "from 15$",
    fanRate: 5,
  },

  {
    id: 4,
    img: "./img/Golden.webp",
    name: "Warriors",
    country: "USA",
    city: "San Francisco",
    champions: 6,
    currentPosition: 7,
    ticketPrice: "from 53$",
    fanRate: 4.5,
  },
  {
    id: 5,
    img: "./img/Denver.webp",
    name: "Nuggets",
    country: 'USA',
    city: "Denver",
    champions: 4,
    currentPosition: 1,
    ticketPrice: "from 45$",
    priceForUkr: "from 15$",
    fanRate: 4,
  },
  {
    id: 6,
    img: "./img/Bulls.webp",
    name: "Bulls",
    country: 'USA',
    city: "Chicago",
    champions: 6,
    currentPosition: 9,
    ticketPrice: "from 45$",
    fanRate: 2.5,
  },
];
