const nbaCardsData = [
  {
    id: 1,
    img: "./img/Raptors.webp",
    name: "Raptors",
    country: 'Canada',
    city: "Toronto",
    champions: 1,
    currentPosition: 9,
    minTicketPrice: 120,
    minPriceForUkr: 65,
    fanRate: 3.5,
  },
  {
    id: 2,
    img: "./img/Lakers.webp",
    name: 'Lakers',
    country: 'USA',
    city: "Los-Angeles",
    champions: 17,
    currentPosition: 7,
    minTicketPrice: 95,
    fanRate: 4,
  },
  {
    id: 3,
    img: "./img/Celtics.webp",
    name: "Celtics",
    country: 'USA',
    city: "Boston",
    champions: 12,
    currentPosition: 2,
    minTicketPrice: 80,
    minPriceForUkr: 50,
    fanRate: 5,
  },

  {
    id: 4,
    img: "./img/Golden.webp",
    name: "Warriors",
    country: "USA",
    city: "San Francisco",
    champions: 6,
    currentPosition: 7,
    minTicketPrice: 75,
    fanRate: 4.5,
  },
  {
    id: 5,
    img: "./img/Denver.webp",
    name: "Nuggets",
    country: 'USA',
    city: "Denver",
    champions: 4,
    currentPosition: 1,
    minTicketPrice: 96,
    minPriceForUkr: 65,
    fanRate: 4,
  },
  {
    id: 6,
    img: "./img/Bulls.webp",
    name: "Bulls",
    country: 'USA',
    city: "Chicago",
    champions: 6,
    currentPosition: 9,
    minTicketPrice: 100,
    fanRate: 2.5,
  },
  {id: 7,
    img: "./img/Raptors.webp",
    name: "Raptors 905",
    country: 'Canada',
    city: "Mississauga",
    champions: "",
    currentPosition: 15,
    minTicketPrice: 25,
    minPriceForUkr: 15,
    fanRate: 1.5,
  },
];
