const nbaCardsData = [
  {
    id: 1,
    img:'./img/Raptors.webp',
    name: "Raptors",
    country: "Canada",
    city: "Toronto",
    champions: 1,
    currentPosition: 9,
    ticketPrice: "from 45$",
  },
  {
    id: 2,
    img:'./img/Lakers.webp',
    name: "Lakers",
    country: "USA",
    city: "Los-Angeles",
    champions: 17,
    currentPosition: 7,
    ticketPrice: "from 35$",
  },
  {
    id: 3,
    img:'./img/Celtics.webp',
    name: "Celtics",
    country: "USA",
    city: "Boston",
    champions: 12,
    currentPosition: 2,
    ticketPrice: "from 42$",
  },
 
  {
    id: 4,
    img:'./img/Golden.webp',
    name: "Warriors",
    country: "USA",
    city: "San Francisco",
    champions: 6,
    currentPosition: 7,
    ticketPrice: "from 53$",

  },
  {
    id: 5,
    img:'./img/Denver.webp',
    name: "Nuggets",
    country: "USA",
    city: "Denver",
    champions: 0,
    currentPosition: 1,
    ticketPrice: "from 45$",
  },
  {
    id: 6,
    img:'./img/Bulls.webp',
    name: "Bulls",
    country: "USA",
    city: "Chicago",
    champions: 6,
    currentPosition: 9,
    ticketPrice: "from 45$",
  },
];
